import { Subject, Chapter, SubjectId, ClassLevel } from './types';

export const SUBJECTS: Subject[] = [
  { id: 'accounts', name: 'Accountancy', icon: 'Calculator', color: 'bg-blue-100 text-blue-700' },
  { id: 'stats', name: 'Statistics', icon: 'BarChart3', color: 'bg-purple-100 text-purple-700' },
  { id: 'ba', name: 'Organization of Commerce', icon: 'Briefcase', color: 'bg-teal-100 text-teal-700' },
  { id: 'eco', name: 'Economics', icon: 'TrendingUp', color: 'bg-green-100 text-green-700' },
  { id: 'english', name: 'English', icon: 'BookOpen', color: 'bg-orange-100 text-orange-700' },
];

export const CHAPTERS: Record<ClassLevel, Record<SubjectId, Chapter[]>> = {
  11: {
    accounts: [
      { id: 'ac11-01', number: 1, title: 'Accounting and its Terminology', description: 'Introduction to basic accounting terms, objectives, and characteristics.' },
      { id: 'ac11-02', number: 2, title: 'Dual Effect of Transactions', description: 'Understanding Types of Accounts and rules of Debit and Credit.' },
      { id: 'ac11-03', number: 3, title: 'Introduction to GST', description: 'Goods and Services Tax: Concept, Characteristics, and Rates.' },
      { id: 'ac11-04', number: 4, title: 'Journal', description: 'Recording transactions in the primary book of entry.' },
      { id: 'ac11-05', number: 5, title: 'Accounting Equation', description: 'Impact of transactions on the accounting equation.' },
      { id: 'ac11-06', number: 6, title: 'Subsidiary Books', description: 'Purchase Book, Sales Book, and Returns Books.' },
      { id: 'ac11-07', number: 7, title: 'Cash Book', description: 'Simple, Two-column, and Three-column Cash Books.' },
      { id: 'ac11-08', number: 8, title: 'Journal Proper', description: 'Recording transactions not covered in other subsidiary books.' },
      { id: 'ac11-09', number: 9, title: 'Ledger and Posting', description: 'Creating accounts and posting from Journal/Subsidiary books.' },
      { id: 'ac11-10', number: 10, title: 'Trial Balance', description: 'Preparation and characteristics of Trial Balance.' },
      { id: 'ac11-11', number: 11, title: 'Bank Reconciliation Statement', description: 'Reconciling Cash Book and Pass Book differences.' },
      { id: 'ac11-12', number: 12, title: 'Rectification of Errors', description: 'Types of errors and their rectification entries.' },
      { id: 'ac11-13', number: 13, title: 'Depreciation', description: 'Concept and methods of calculating depreciation.' },
      { id: 'ac11-14', number: 14, title: 'Provisions and Reserves', description: 'Types and importance of provisions and reserves.' },
      { id: 'ac11-15', number: 15, title: 'Final Accounts', description: 'Trading Account, Profit & Loss Account, and Balance Sheet.' },
    ],
    stats: [
      { id: 'st11-01', number: 1, title: 'Collection of Data', description: 'Primary vs Secondary data, methods of collection.' },
      { id: 'st11-02', number: 2, title: 'Presentation of Data', description: 'Tabulation, Diagrams, and Graphical representation.' },
      { id: 'st11-03', number: 3, title: 'Measures of Central Tendency', description: 'Mean, Median, Mode, Quartiles, Deciles, Percentiles.' },
      { id: 'st11-04', number: 4, title: 'Measures of Dispersion', description: 'Range, Deviation, Variance, and Coefficient of Variation.' },
      { id: 'st11-05', number: 5, title: 'Skewness', description: 'Karl Pearson and Bowley methods of skewness.' },
      { id: 'st11-06', number: 6, title: 'Permutations and Combinations', description: 'Fundamental principles of counting and binomial expansion.' },
      { id: 'st11-07', number: 7, title: 'Sampling Methods', description: 'Population, Sample, SRS, Stratified, and Systematic sampling.' },
      { id: 'st11-08', number: 8, title: 'Function', description: 'Domain, Co-domain, Range, and types of functions.' },
      { id: 'st11-09', number: 9, title: 'Geometric Progression', description: 'Meaning, nth term, and sum of n terms.' },
    ],
    ba: [
      { id: 'ba11-01', number: 1, title: 'Nature, Purpose and Scope of Business', description: 'Economic activities, Business, Profession, and Employment.' },
      { id: 'ba11-02', number: 2, title: 'Business Services - I', description: 'Insurance, Postal, and Warehousing services.' },
      { id: 'ba11-03', number: 3, title: 'Business Services - II', description: 'Banking services, E-banking, and Bank accounts.' },
      { id: 'ba11-04', number: 4, title: 'Forms of Business Organisation - I', description: 'Sole Proprietorship, HUF, and Partnership.' },
      { id: 'ba11-05', number: 5, title: 'Forms of Business Organisation - II', description: 'Co-operative Societies and Joint Stock Companies.' },
      { id: 'ba11-06', number: 6, title: 'Public, Private & Global Enterprises', description: 'Departmental Undertaking, Statutory Corp, MNCs.' },
      { id: 'ba11-07', number: 7, title: 'Business Modes', description: 'E-business, Outsourcing (BPO, KPO).' },
      { id: 'ba11-08', number: 8, title: 'Sources of Business Finance', description: 'Owners funds vs Borrowed funds, Equity, Debentures.' },
      { id: 'ba11-09', number: 9, title: 'Internal Trade', description: 'Wholesale and Retail trade, GST implications.' },
      { id: 'ba11-10', number: 10, title: 'International Trade', description: 'Import-Export procedures and documents.' },
      { id: 'ba11-11', number: 11, title: 'Social Responsibility of Business', description: 'Ethics and responsibility towards stakeholders.' },
    ],
    eco: [
      { id: 'ec11-01', number: 1, title: 'Economics: An Introduction', description: 'Subject matter, Micro vs Macro, Statistics in Economics.' },
      { id: 'ec11-02', number: 2, title: 'Fundamental Concepts', description: 'Price, Value, Goods, Services, Wealth, and Welfare.' },
      { id: 'ec11-03', number: 3, title: 'Demand', description: 'Law of Demand, Determinants, Elasticity of Demand.' },
      { id: 'ec11-04', number: 4, title: 'Supply', description: 'Law of Supply, Determinants, Market Equilibrium.' },
      { id: 'ec11-05', number: 5, title: 'Cost of Production & Revenue', description: 'Fixed, Variable, Marginal Cost, and Revenue concepts.' },
      { id: 'ec11-06', number: 6, title: 'Market', description: 'Perfect Competition, Monopoly, Monopolistic Competition.' },
      { id: 'ec11-07', number: 7, title: 'Indian Economy', description: 'Ancient economy, Colonial impact, and Independence.' },
      { id: 'ec11-08', number: 8, title: 'Economic Reforms', description: 'Liberalization, Privatization, and Globalization (LPG).' },
      { id: 'ec11-09', number: 9, title: 'National Income', description: 'Concepts of GDP, GNP, NNP, and measurement methods.' },
      { id: 'ec11-10', number: 10, title: 'Budget', description: 'Types of Budget, Objectives, and Fiscal Policy.' },
    ],
    english: [
      { id: 'en11-01', number: 1, title: 'The Portrait of a Lady', description: 'Prose by Khushwant Singh.' },
      { id: 'en11-02', number: 2, title: 'A Photograph', description: 'Poem by Shirley Toulson.' },
      { id: 'en11-03', number: 3, title: "We're Not Afraid to Die", description: 'Prose about a sea voyage.' },
      { id: 'en11-04', number: 4, title: 'Discovering Tut', description: 'The Saga Continues.' },
      { id: 'en11-05', number: 5, title: 'The Laburnum Top', description: 'Poem by Ted Hughes.' },
      { id: 'en11-06', number: 6, title: 'The Voice of the Rain', description: 'Poem by Walt Whitman.' },
      { id: 'en11-07', number: 7, title: 'The Ailing Planet', description: 'The Green Movement\'s Role.' },
      { id: 'en11-08', number: 8, title: 'The Browning Version', description: 'Play script.' },
      { id: 'en11-09', number: 9, title: 'Childhood', description: 'Poem by Markus Natten.' },
      { id: 'en11-10', number: 10, title: 'Silk Road', description: 'Travelogue.' },
    ]
  },
  12: {
    accounts: [
      { id: 'ac12-01', number: 1, title: 'Introduction to Partnership', description: 'Nature, Deed, and Provisions.' },
      { id: 'ac12-02', number: 2, title: 'Final Accounts of Partnership', description: 'Trading, PL, PL Appropriation, and Balance Sheet.' },
      { id: 'ac12-03', number: 3, title: 'Valuation of Goodwill', description: 'Average Profit, Super Profit, and Capitalization methods.' },
      { id: 'ac12-04', number: 4, title: 'Reconstruction of Partnership', description: 'Change in Profit Sharing Ratio (Sacrifice/Gain).' },
      { id: 'ac12-05', number: 5, title: 'Admission of a Partner', description: 'Revaluation, Goodwill treatment, and Capital adjustment.' },
      { id: 'ac12-06', number: 6, title: 'Retirement/Death of a Partner', description: 'Settlement of claims and capital adjustments.' },
      { id: 'ac12-07', number: 7, title: 'Dissolution of Partnership Firm', description: 'Realisation Account and settlement of accounts.' },
      { id: 'ac12-08', number: 8, title: 'Share Capital Transactions', description: 'Issue, Forfeiture, and Reissue of Shares.' },
      { id: 'ac12-09', number: 9, title: 'Accounting for Debentures', description: 'Issue and Redemption of Debentures.' },
      { id: 'ac12-10', number: 10, title: 'Company Final Accounts', description: 'Schedule III Balance Sheet and PL Statement.' },
      { id: 'ac12-11', number: 11, title: 'Analysis of Financial Statements', description: 'Tools: Comparative and Common Size Statements.' },
      { id: 'ac12-12', number: 12, title: 'Accounting Ratios', description: 'Liquidity, Solvency, Activity, and Profitability ratios.' },
      { id: 'ac12-13', number: 13, title: 'Cash Flow Statement', description: 'Operating, Investing, and Financing activities.' },
    ],
    stats: [
      { id: 'st12-01', number: 1, title: 'Index Number', description: 'Fixed/Chain base, Cost of Living Index, Weighted Average.' },
      { id: 'st12-02', number: 2, title: 'Linear Correlation', description: 'Scatter diagram, Karl Pearson\'s, and Spearman\'s Rank.' },
      { id: 'st12-03', number: 3, title: 'Linear Regression', description: 'Regression lines, Coefficients, and properties.' },
      { id: 'st12-04', number: 4, title: 'Time Series', description: 'Trend analysis, Moving Averages, Seasonal variations.' },
      { id: 'st12-05', number: 5, title: 'Probability', description: 'Events, Conditional Probability, Multiplication Law.' },
      { id: 'st12-06', number: 6, title: 'Random Variable & Distribution', description: 'Discrete variable, Mean, and Variance.' },
      { id: 'st12-07', number: 7, title: 'Normal Distribution', description: 'Properties and area under the standard normal curve.' },
      { id: 'st12-08', number: 8, title: 'Limit', description: 'Concept, Working rules, and Standard forms.' },
      { id: 'st12-09', number: 9, title: 'Differentiation', description: 'Rules of derivative, Second order, Applications.' },
    ],
    ba: [
      { id: 'ba12-01', number: 1, title: 'Nature and Significance of Management', description: 'Levels, Functions, and Coordination.' },
      { id: 'ba12-02', number: 2, title: 'Principles of Management', description: 'Fayol\'s Principles and Taylor\'s Scientific Management.' },
      { id: 'ba12-03', number: 3, title: 'Planning', description: 'Process, Types of Plans, and Importance.' },
      { id: 'ba12-04', number: 4, title: 'Organizing', description: 'Structure, Delegation, and Decentralization.' },
      { id: 'ba12-05', number: 5, title: 'Staffing', description: 'Recruitment, Selection, Training, and Development.' },
      { id: 'ba12-06', number: 6, title: 'Directing', description: 'Supervision, Motivation, Leadership, Communication.' },
      { id: 'ba12-07', number: 7, title: 'Controlling', description: 'Process and relationship with Planning.' },
      { id: 'ba12-08', number: 8, title: 'Financial Management', description: 'Capital Structure, Working Capital, Fixed Capital.' },
      { id: 'ba12-09', number: 9, title: 'Financial Market', description: 'Money Market, Capital Market, SEBI.' },
      { id: 'ba12-10', number: 10, title: 'Marketing Management', description: '4Ps: Product, Price, Place, Promotion.' },
      { id: 'ba12-11', number: 11, title: 'Consumer Protection', description: 'Rights, Responsibilities, and Redressal agencies.' },
      { id: 'ba12-12', number: 12, title: 'Business Environment', description: 'Dimensions: Economic, Social, Legal, Political, Tech.' },
    ],
    eco: [
      { id: 'ec12-01', number: 1, title: 'Graph in Economics', description: 'Importance and types of diagrams/graphs.' },
      { id: 'ec12-02', number: 2, title: 'Indicators of Growth & Development', description: 'GDP, Per Capita Income, PQLI, HDI.' },
      { id: 'ec12-03', number: 3, title: 'Money and Inflation', description: 'Functions of money, Causes and Types of Inflation.' },
      { id: 'ec12-04', number: 4, title: 'Banking and Monetary Policy', description: 'Commercial Banks, Central Bank (RBI) functions.' },
      { id: 'ec12-05', number: 5, title: 'Poverty', description: 'Indicators, Causes, and Poverty Alleviation Programmes.' },
      { id: 'ec12-06', number: 6, title: 'Unemployment', description: 'Types, Causes, and Measures to reduce unemployment.' },
      { id: 'ec12-07', number: 7, title: 'Population', description: 'Trends in India, Demographic Transition, Control measures.' },
      { id: 'ec12-08', number: 8, title: 'Agriculture Sector', description: 'Importance, Problems, and Green Revolution.' },
      { id: 'ec12-09', number: 9, title: 'Foreign Trade', description: 'Direction, Composition, and Balance of Payments.' },
      { id: 'ec12-10', number: 10, title: 'Industrial Sector', description: 'Structure, Importance, and Industrial Policies.' },
      { id: 'ec12-11', number: 11, title: 'Emerging Issues in Indian Economy', description: 'Migration, Urbanization, Infrastructure.' },
    ],
    english: [
      { id: 'en12-01', number: 1, title: 'The Last Lesson', description: 'Importance of language.' },
      { id: 'en12-02', number: 2, title: 'Lost Spring', description: 'Stories of Stolen Childhood.' },
      { id: 'en12-03', number: 3, title: 'Deep Water', description: 'Overcoming fear.' },
      { id: 'en12-04', number: 4, title: 'The Rattrap', description: 'Metaphor of the world as a rattrap.' },
      { id: 'en12-05', number: 5, title: 'Indigo', description: 'Gandhi and the Champaran episode.' },
      { id: 'en12-06', number: 6, title: 'My Mother at Sixty-six', description: 'Poem on aging and separation.' },
      { id: 'en12-07', number: 7, title: 'An Elementary School Classroom', description: 'Poem on social injustice.' },
      { id: 'en12-08', number: 8, title: 'Keeping Quiet', description: 'Poem on introspection.' },
      { id: 'en12-09', number: 9, title: 'A Thing of Beauty', description: 'Poem by John Keats.' },
      { id: 'en12-10', number: 10, title: 'Aunt Jennifer\'s Tigers', description: 'Poem on constraints of married life.' },
    ]
  }
};